platform :ios, '13.0'
use_frameworks! :linkage => :static
#use_modular_headers!
inhibit_all_warnings!
install! 'cocoapods',
  :warn_for_unused_master_specs_repo => false,
  :preserve_pod_file_structure => true

source 'git@github.com:GoveeHomeApp/GHSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'GHLightInference_Example' do
  pod 'GHLightInference', :path => '../'
  pod 'LibTorch-Lite', '~>1.10.0'
  pod 'HandyJSON', :git => 'git@github.com:alibaba/HandyJSON.git', :tag => '5.0.2'
  
end
