platform :ios, '13.0'
use_frameworks! :linkage => :static
#use_modular_headers!
inhibit_all_warnings!
install! 'cocoapods',
  :warn_for_unused_master_specs_repo => false,
  :preserve_pod_file_structure => true

source 'git@github.com:GoveeHomeApp/GHSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'GHLightInference_Example' do
  pod 'GHLightInference', :path => '../'
  pod 'LibTorch-Lite', '~>1.13.0.1'
  pod 'HandyJSON', :git => 'git@github.com:alibaba/HandyJSON.git', :tag => '5.0.2'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'HandyJSON-watchOS' || target.name == 'HandyJSON-iOS' || target.name == 'HandyJSON'
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
          config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
        end
      end
    end
  end
end
